### ISSUE TITLE
改了一下内存问题,增加了文字阴影功能,单纯实现REPET_CONTINUOUS的方式

### ISSUE THREAD

**Issue by zhaimi** [385841539/MarqueeView#9]
public class MarqueeView extends View {

    private String string;//最终绘制的文本
    private float speed = 1;//移动速度
    private int textColor = Color.BLACK;//文字颜色,默认黑色
    private float textSize = 12;//文字颜色,默认黑色
    private float startLocationDistance = 0.5f;//开始的位置选取，百分比来的，距离左边，0~1，0代表不间距，1的话代表，从右面，1/2代表中间。
    private int itemDistance = 4; //默认item间隔4个空格

    private boolean hasShadow = false;
    private float shadowDy = 0f;
    private float shadowDx = 0f;
    private float shadowRadius = 0f;
    private int shadowColor = Color.BLACK;

    private boolean isResetLocation = true;//默认为true
    private float xLocation = 0;//文本的x坐标
    private int contentWidth;//内容的宽度

    private volatile boolean isRoll = false;//是否继续滚动

    private TextPaint paint;//画笔
    private Rect rect;

    private boolean resetInit = true;

    private String content = "";

    private float textHeight;

   
    private Handler mHandler = new Handler(new Handler.Callback() { //替换Thread,采用handler,推荐使用 WeakHandler,这里就不更换了
        @Override
        public boolean handleMessage(Message msg) {
            if (msg.what == 1) {
                if (isRoll && !TextUtils.isEmpty(content)) {
                    xLocation = xLocation - speed;
                    postInvalidate();//每隔10毫秒重绘视图
                    mHandler.sendEmptyMessageDelayed(1, 30);
                }
                return true;
            }
            return false;

        }
    });

    public MarqueeView(Context context) {
        this(context, null);
    }

    public MarqueeView(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public MarqueeView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        initAttrs(attrs);
        initPaint();
    }

    @SuppressLint("RestrictedApi")
    private void initAttrs(AttributeSet attrs) {
        TintTypedArray tta = TintTypedArray.obtainStyledAttributes(getContext(), attrs,
                R.styleable.MarqueeView);

        textColor = tta.getColor(R.styleable.MarqueeView_marqueeview_text_color, textColor);
        isResetLocation = tta.getBoolean(R.styleable.MarqueeView_marqueeview_is_resetLocation, isResetLocation);
        speed = tta.getFloat(R.styleable.MarqueeView_marqueeview_text_speed, speed);
        textSize = tta.getFloat(R.styleable.MarqueeView_marqueeview_text_size, textSize);
        startLocationDistance = tta.getFloat(R.styleable.MarqueeView_marqueeview_text_startlocationdistance, startLocationDistance);
        itemDistance = tta.getInt(R.styleable.MarqueeView_marqueeview_text_distance, itemDistance);
        hasShadow = tta.getBoolean(R.styleable.MarqueeView_marqueeview_text_shadow, false);
        shadowDx = tta.getFloat(R.styleable.MarqueeView_marqueeview_text_shadow_dx, 0);
        shadowDy = tta.getFloat(R.styleable.MarqueeView_marqueeview_text_shadow_dy, 0);
        shadowRadius = tta.getFloat(R.styleable.MarqueeView_marqueeview_text_shadow_radius, 0);
        shadowColor = tta.getColor(R.styleable.MarqueeView_marqueeview_text_shadow_color, shadowColor);
        tta.recycle();
    }

    /**
     * 刻字机修改
     */
    private void initPaint() {
        rect = new Rect();
        paint = new TextPaint(Paint.ANTI_ALIAS_FLAG);//初始化文本画笔
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(textColor);//文字颜色值,可以不设定
        paint.setTextSize(PixelUtil.sp2px(textSize));//文字大小
        if (hasShadow) {
            paint.setShadowLayer(shadowRadius, shadowDx, shadowDy, shadowColor);
        }
    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);
        if (resetInit) {
            if (startLocationDistance < 0) {
                startLocationDistance = 0;
            } else if (startLocationDistance > 1) {
                startLocationDistance = 1;
            }
            xLocation = startLocationDistance;
            resetInit = false;
        }
        if (isRoll) {
            if (xLocation <= -(contentWidth + getBlankWidth() * itemDistance)) {
                xLocation = xLocation + contentWidth + getBlankWidth() * itemDistance;
                string = string + content;
                //调用pattern.quote ,防止replaceFirst中含有特殊字符比如完整的(),导致的crash
                string = string.replaceFirst(pattern.quote(""+content), "");   //修改内存问题,防止文字长度不断增加导致内存溢出的情况,
            }
        }

        //把文字画出来
        if (string != null) {
            canvas.drawText(string, xLocation, getHeight() / 2 + textHeight / 2, paint);
        }

    }

    /**
     * 继续滚动
     */
    public void continueRoll() {
        postInvalidate();
        mHandler.removeMessages(1);
        isRoll = true;
        mHandler.sendEmptyMessage(1);
    }

    /**
     * 停止滚动
     */
    public void stopRoll() {
        isRoll = false;
        resetInit = true;
        mHandler.removeMessages(1);
        postInvalidate();
    }

    public void setTextColor(int color) {
        textColor = color;
        paint.setColor(color);
        postInvalidate();
    }

    private float getContentWidth(String black) {
        if (TextUtils.isEmpty(black)) {
            return 0;
        }

        if (rect == null) {
            rect = new Rect();
        }
        paint.getTextBounds(black, 0, black.length(), rect);
        textHeight = getContentHeight();

        return rect.width();
    }

    /**
     * http://blog.csdn.net/u014702653/article/details/51985821
     * 详细解说了
     *
     * @param
     * @return
     */
    private float getContentHeight() {
        Paint.FontMetrics fontMetrics = paint.getFontMetrics();
        return Math.abs((fontMetrics.bottom - fontMetrics.top)) / 2;
    }

    /**
     * 计算出一个空格的宽度
     */
    private float getBlankWidth() {
        String text1 = "en en";
        String text2 = "enen";
        return getContentWidth(text1) - getContentWidth(text2);

    }

    /**
     * 添加文字
     * @param content 显示文字的内容
     * @param needRoll 是否需要滚动,如果不需要,就把文字定位到startLocationDistance的位置,而且不重复
     */
    public void setContent(String content, boolean needRoll) {
        if (TextUtils.isEmpty(content)) {
            return;
        }

        isResetLocation = true;
        resetInit = true;
        if (needRoll) {
            for (int i = 0; i < itemDistance; i++) {
                content = content + " ";
            }
            this.content = content;
            contentWidth = (int) (getContentWidth(content));//可以理解为一个单元内容的长度
            int contentCount = (getWidth() / contentWidth) + 2;
            this.string = "";
            for (int i = 0; i <= contentCount + 2; i++) {
                this.string = String.format("%s%s", this.string, this.content);//根据重复次数去叠加。
            }
            postInvalidate();
        } else {
            stopRoll();
            resetInit = true;
            getContentWidth(content);
            this.content = content;  //如果不需要滚动,就直接走这里了
            this.string = content;
            postInvalidate();
        }

    }

}

========================== attrs.xml================

<declare-styleable name="MarqueeView">
        <attr name="marqueeview_text_distance" format="integer" />
        <attr name="marqueeview_text_startlocationdistance" format="float" />

        <attr name="marqueeview_text_speed" format="float" />
        <attr name="marqueeview_text_color" format="color|reference" />
        <attr name="marqueeview_text_size" format="float" />

        <attr name="marqueeview_is_resetLocation" format="boolean" />

        <attr name="marqueeview_text_shadow" format="boolean" /> 
        <attr name="marqueeview_text_shadow_radius" format="float" /> 
        <attr name="marqueeview_text_shadow_dx" format="float" /> 
        <attr name="marqueeview_text_shadow_dy" format="float" /> 
        <attr name="marqueeview_text_shadow_color" format="color" /> 

    </declare-styleable>

**Comment by zhaimi** [comment]
重新写了一下大神的源码.放弃了Thread的方式(thread容易引起内存泄漏的问题,推荐使用WeakHandler 等,
目前还有个小问题就是文字的位置,需要细调一下..懒得改了,因为已经够用了

**Comment by firefly5927** [comment]
这个问题，提pr更好

**Comment by MIkeeJY** [comment]
@zhaimi  文字位置如何记录啊 这个每次切换都从头开始

**Comment by zhaimi** [comment]
@MIkeeJY 是替换文字还是 生命周期 onPause onResume时? 如果是切换画面走生命周期的话, 可以写个
/**
 * 停止滚动
 */
public void pauseRoll() {
    isRoll = false;
    //resetInit = true;   // 这段代码注释掉,就可以了, 这样在onDraw方法中就不会重新定位了
    mHandler.removeMessages(1);
    postInvalidate();
}

**Comment by MIkeeJY** [comment]
@zhaimi  感谢可以了

**Comment by tianshaokai** [comment]
这个是否可以改成 任意view呢，比如自定义view实现一个跑马灯效果，或者实现上下滚动效果
